version: '2.4'
services:
  cnos:
    image: cnos
    privileged: true
    build:
      context: ../object_detectors/cnos_sasha
      dockerfile: Dockerfile
      shm_size: '2gb'
    shm_size: '2gb'
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../object_detectors/cnos_sasha/:/code
      - ../object_detectors/cnos_sasha/torch_cache:/root/.cache/torch
    environment: 
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    env_file: ../config/ros.env
    command: bash -c "source /opt/ros/noetic/setup.bash; source /root/catkin_ws/devel/setup.bash;
                      /bin/bash"
    stdin_open: true
    tty: true 

  zs6d:
    image: zs6d
    build:
      context: ../pose_estimators/zs6d_sasha/
      dockerfile: Dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - "../pose_estimators/zs6d_sasha/:/code:rw"
      - "../pose_estimators/zs6d_sasha/torch_cache:/root/.cache/torch:rw"
      - "../datasets/ycbv/models:/code/templates/ycbv/models"
      - ../config:/root/config
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    env_file: ../config/ros.env
    command: bash -c "source /opt/ros/noetic/setup.bash; source /root/catkin_ws/devel/setup.bash;
                      /bin/bash"        
    privileged: true
    stdin_open: true
    tty: true
