version: '2.4'
services:
  grounded_sam2_ros:
    image: grounded_sam2_ros
    privileged: true
    build:
      context: ../object_detectors/grounded_sam2_ros
      dockerfile: Dockerfile_ros
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../torch_cache/gsam2/:/root/.cache/torch
    environment: 
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    env_file: ../config/ros.env
    command: bash -c "source /opt/ros/noetic/setup.bash; source /root/catkin_ws/devel/setup.bash; python3.10 -m pip install --no-build-isolation -e grounding_dino; rosrun grounded_sam_2 grounded_sam_2_ros.py"
    stdin_open: true
    tty: true 
