version: '2.4'
services:
  grounded_sam2_ros:
    image: grounded_sam2_ros
    privileged: true
    build:
      context: ..
      dockerfile: Dockerfile_ros
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../torch_cache/gsam2/:/root/.cache/torch
      - ../object_detectors/grounded_sam2_ros:/root/grounded_sam2
      - ../object_detectors/Depth-Anything-V2:/root/Depth-Anything-V2
      - ../workspace:/root/workspace
    environment: 
      # - DISPLAY=$DISPLAY
      # - QT_X11_NO_MITSHM=1
      # - NVIDIA_DRIVER_CAPABILITIES=all
      # - MPLBACKEND=Qt5Agg
      
      # From HSR docker-compose.yml
      # Display X Server GUIs.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # Configure the Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=10.1
      - DOCKER_RUNTIME=${DOCKER_RUNTIME}
      # Configure the PulseAudio interface.
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    env_file: ../config/ros.env
    command: bash -c "source /opt/ros/noetic/setup.bash; source /root/catkin_ws/devel/setup.bash; rosrun grounded_sam_2 grounded_sam_2_ros.py"
    stdin_open: true
    tty: true 
